version: "3.8"

services:
  hgs_app:
    build: app
    container_name: hgs_app
    hostname: hgs_app
    volumes:
      - /var/hgs_re3:/var/hgs_re3
    restart: always
    depends_on:
      - hgs_memcached
      - hgs_redis
    ports:
      - "9000:9000"
    networks:
      - hgs_net

  hgs_memcached:
    image: memcached:1.6-alpine
    container_name: hgs_memcached
    restart: always
    networks:
      - hgs_net

  hgs_redis:
    image: redis:7.2-alpine
    container_name: hgs_redis
    restart: always
    networks:
      - hgs_net

  hgs_mongo:
    image: mongo:7.0-jammy
    container_name: hgs_mongodb
    restart: always
    environment:
 #     MONGO_INITDB_ROOT_USERNAME: hgs
 #     MONGO_INITDB_ROOT_PASSWORD: hgshgs
      MONGO_INITDB_DATABASE: hgs
      TZ: Asia/Tokyo
    networks:
      - hgs_net
    ports:
      - "27018:27017"
    volumes:
      - hgs_mongo_vol:/data/db
      - hgs_mongo_config_vol:/data/configdb
      - /var/hgs_re3/docker/dev/mongo_backup:/tmp/backup

volumes:
  hgs_mongo_vol:
  hgs_mongo_config_vol:
  hgs_redis_vol:

networks:
  hgs_net:

